services:
  db:
    image: mariadb:10.11
    environment:
      MARIADB_ROOT_PASSWORD: rootpass
      MARIADB_USER: mailadmin
      MARIADB_PASSWORD: iBMVRf8bLP7vN49C5YmT
      MARIADB_DATABASE: mailadmin_development
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./db/grant.sql:/docker-entrypoint-initdb.d/grant.sql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
    volumes:
      - .:/app

volumes:
  db-data:
